#ifndef QADCMODULES_GLOBAL_H
#define QADCMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QADCMODULES_LIBRARY)
#  define QADCMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QADCMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QARCADISUTIL_GLOBAL_H
