#!/bin/bash

mkdir adcircmodules
cp -d ../build/_adcircmodules.so adcircmodules/.

cat ../build/adcircmodules.py \
 | sed '/^# This file was automatically generated by SWIG/,/^del _swig_python_version_info$/d' \
 | cat <(echo "from . import _adcircmodules") - \
 > adcircmodules/__init__.py

python setup.py bdist_wheel
cd dist

for wheel in $(find . -iname "*.whl") ; do 
  mv $wheel $(echo $wheel | sed 's/-linux_/-manylinux1_/')
done
