#!/bin/bash

rm -rf pyadcircmodules pyadcircmodules.egg-info build dist bin
mkdir pyadcircmodules

cp ../build/_pyadcircmodules.so pyadcircmodules/.
cp ../../deps/share/proj/proj.db pyadcircmodules/.
cp ../build/interpolateAdcircStations pyadcircmodules/.
cp ../build/generateAdcircSimulationDates pyadcircmodules/.

strip --strip-unneeded pyadcircmodules/_pyadcircmodules.so
strip --strip-unneeded bin/interpolateAdcircStations
strip --strip-unneeded bin/generateAdcircSimulationDates

cat ../build/pyadcircmodules.py  \
	| sed '/^# This file was automatically generated by SWIG/,/^del _swig_python_version_info$/d' \
	| cat <(echo "from . import _pyadcircmodules") - \
	> tmp.py 

cat scripts/environment.py tmp.py > pyadcircmodules/__init__.py
rm tmp.py

/opt/python/cp38-cp38/bin/python3 setup.py bdist_wheel
/opt/python/cp39-cp39/bin/python3 setup.py bdist_wheel


for wheel in $(find . -name "*.whl")
do
    mv $wheel $(echo $wheel | sed 's/-linux_/-manylinux1_/')
done
