#ifndef ADCIRCMODULES_GLOBAL_H
#define ADCIRCMODULES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADCIRCMODULES_LIBRARY)
#  define ADCIRCMODULESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADCIRCMODULESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADCIRCMODULES_GLOBAL_H
